const allPlayers = [
  {
    "id": "shakira-austin-3z8uacbqmewp",
    "name": "Shakira Austin",
    "team": "",
    "position": "F",
    "height": "6-5",
    "jersey": "",
    "wnbaTeam": "Washington Mystics",
    "profile": "https://www.unrivaled.basketball/player/shakira-austin-3z8uacbqmewp",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/shakira-austin/images/headshot.jpg?v=1767477910175"
  },
  {
    "id": "monique-billings-3i2p8x364hv1",
    "name": "Monique Billings",
    "team": "",
    "position": "F",
    "height": "6-4",
    "jersey": "",
    "wnbaTeam": "Indiana Fever",
    "profile": "https://www.unrivaled.basketball/player/monique-billings-3i2p8x364hv1",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/monique-billings/images/headshot.jpg?v=1767477441875"
  },
  {
    "id": "aliyah-boston-v63b2ehlrlnu",
    "name": "Aliyah Boston",
    "team": "",
    "position": "F",
    "height": "6-5",
    "jersey": "",
    "wnbaTeam": "Indiana Fever",
    "profile": "https://www.unrivaled.basketball/player/aliyah-boston-v63b2ehlrlnu",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/aliyah-boston/images/headshot.jpg?v=1767477838874"
  },
  {
    "id": "cameron-brink-9z9kphgbukqm",
    "name": "Cameron Brink",
    "team": "",
    "position": "F",
    "height": "6-4",
    "jersey": "",
    "wnbaTeam": "Los Angeles Sparks",
    "profile": "https://www.unrivaled.basketball/player/cameron-brink-9z9kphgbukqm",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/cameron-brink/images/headshot.jpg?v=1767477189700"
  },
  {
    "id": "paige-bueckers-osz1lblmgodi",
    "name": "Paige Bueckers",
    "team": "",
    "position": "G",
    "height": "6-0",
    "jersey": "",
    "wnbaTeam": "Dallas Wings",
    "profile": "https://www.unrivaled.basketball/player/paige-bueckers-osz1lblmgodi",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/paige-bueckers/images/headshot.jpg?v=1767477248431"
  },
  {
    "id": "rae-burrell-2pg47b3qi9z6",
    "name": "Rae Burrell",
    "team": "",
    "position": "W",
    "height": "6-2",
    "jersey": "",
    "wnbaTeam": "Los Angeles Sparks",
    "profile": "https://www.unrivaled.basketball/player/rae-burrell-2pg47b3qi9z6",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/rae-burrell/images/headshot.jpg?v=1767478268108"
  },
  {
    "id": "veronica-burton-1zy3eeoe1a2m",
    "name": "Veronica Burton",
    "team": "",
    "position": "G",
    "height": "5-9",
    "jersey": "",
    "wnbaTeam": "Golden State Valkyries",
    "profile": "https://www.unrivaled.basketball/player/veronica-burton-1zy3eeoe1a2m",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/veronica-burton/images/headshot.jpg?v=1767477769734"
  },
  {
    "id": "jordin-canada-t38wmgweal5r",
    "name": "Jordin Canada",
    "team": "",
    "position": "G",
    "height": "5-6",
    "jersey": "",
    "wnbaTeam": "Atlanta Dream",
    "profile": "https://www.unrivaled.basketball/player/jordin-canada-t38wmgweal5r",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/jordin-canada/images/headshot.jpg?v=1767477620203"
  },
  {
    "id": "bridget-carleton-vwkebljbwhyb",
    "name": "Bridget Carleton",
    "team": "",
    "position": "",
    "height": "",
    "jersey": "",
    "wnbaTeam": "Portland Fire",
    "profile": "https://www.unrivaled.basketball/player/bridget-carleton-vwkebljbwhyb",
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3906972.png"
  },
  {
    "id": "dijonai-carrington-pcmzjnqrhipe",
    "name": "DiJonai Carrington",
    "team": "",
    "position": "W",
    "height": "5-11",
    "jersey": "",
    "wnbaTeam": "Chicago Sky",
    "profile": "https://www.unrivaled.basketball/player/dijonai-carrington-pcmzjnqrhipe",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/dijonai-carrington/images/headshot.jpg?v=1738721358602"
  },
  {
    "id": "sonia-citron-9e602707s6ru",
    "name": "Sonia Citron",
    "team": "",
    "position": "W",
    "height": "6-1",
    "jersey": "",
    "wnbaTeam": "Washington Mystics",
    "profile": "https://www.unrivaled.basketball/player/sonia-citron-9e602707s6ru",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/sonia-citron/images/headshot.jpg?v=1767477456232"
  },
  {
    "id": "natasha-cloud-pwrq626gh7a3",
    "name": "Natasha Cloud",
    "team": "",
    "position": "G",
    "height": "5-10",
    "jersey": "",
    "wnbaTeam": "Chicago Sky",
    "profile": "https://www.unrivaled.basketball/player/natasha-cloud-pwrq626gh7a3",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/natasha-cloud/images/headshot.jpg?v=1767477849957"
  },
  {
    "id": "napheesa-collier-bcggk95vccg5",
    "name": "Napheesa Collier",
    "team": "",
    "position": "F",
    "height": "6-1",
    "jersey": "",
    "wnbaTeam": "Minnesota Lynx",
    "profile": "https://www.unrivaled.basketball/player/napheesa-collier-bcggk95vccg5",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/napheesa-collier/images/headshot.jpg?v=1767477668619"
  },
  {
    "id": "kahleah-copper-2k18gfn8wsmb",
    "name": "Kahleah Copper",
    "team": "",
    "position": "W",
    "height": "6-1",
    "jersey": "",
    "wnbaTeam": "Phoenix Mercury",
    "profile": "https://www.unrivaled.basketball/player/kahleah-copper-2k18gfn8wsmb",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/kahleah-copper/images/headshot.jpg?v=1767477918565"
  },
  {
    "id": "skylar-diggins-rkjud3az38vq",
    "name": "Skylar Diggins",
    "team": "",
    "position": "G",
    "height": "5-9",
    "jersey": "",
    "wnbaTeam": "Chicago Sky",
    "profile": "https://www.unrivaled.basketball/player/skylar-diggins-rkjud3az38vq",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/skylar-diggins/images/headshot.jpg?v=1767477677611"
  },
  {
    "id": "aaliyah-edwards-vuytsg7bv3o1",
    "name": "Aaliyah Edwards",
    "team": "",
    "position": "F",
    "height": "6-3",
    "jersey": "",
    "wnbaTeam": "Connecticut Sun",
    "profile": "https://www.unrivaled.basketball/player/aaliyah-edwards-vuytsg7bv3o1",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/aaliyah-edwards/images/headshot.jpg?v=1767477687510"
  },
  {
    "id": "temi-fagbenle-jofrbvhakq4h",
    "name": "Temi Fágbénlé",
    "team": "",
    "position": "F",
    "height": "6-4",
    "jersey": "",
    "wnbaTeam": "Toronto Tempo",
    "profile": "https://www.unrivaled.basketball/player/temi-fagbenle-jofrbvhakq4h",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/temi-fagbenle/images/headshot.png?v=1767900426323"
  },
  {
    "id": "chelsea-gray-r6go6kmzp23j",
    "name": "Chelsea Gray",
    "team": "",
    "position": "G",
    "height": "5-11",
    "jersey": "",
    "wnbaTeam": "Las Vegas Aces",
    "profile": "https://www.unrivaled.basketball/player/chelsea-gray-r6go6kmzp23j",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/chelsea-gray/images/headshot.jpg?v=1767477920415"
  },
  {
    "id": "allisha-gray-5df4bg3v8c9g",
    "name": "Allisha Gray",
    "team": "",
    "position": "G",
    "height": "6-0",
    "jersey": "",
    "wnbaTeam": "Atlanta Dream",
    "profile": "https://www.unrivaled.basketball/player/allisha-gray-5df4bg3v8c9g",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/allisha-gray/images/headshot.jpg?v=1767479359378"
  },
  {
    "id": "dearica-hamby-4prx3vxu62om",
    "name": "Dearica Hamby",
    "team": "",
    "position": "F",
    "height": "6-3",
    "jersey": "",
    "wnbaTeam": "Los Angeles Sparks",
    "profile": "https://www.unrivaled.basketball/player/dearica-hamby-4prx3vxu62om",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/dearica-hamby/images/headshot.jpg?v=1767478305619"
  },
  {
    "id": "tiffany-hayes-pfchl0hhtbmu",
    "name": "Tiffany Hayes",
    "team": "",
    "position": "G",
    "height": "5-10",
    "jersey": "",
    "wnbaTeam": "Golden State Valkyries",
    "profile": "https://www.unrivaled.basketball/player/tiffany-hayes-pfchl0hhtbmu",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/tiffany-hayes/images/headshot.jpg?v=1767479257583"
  },
  {
    "id": "natisha-hiedeman-okjofgwlkna9",
    "name": "Natisha Hiedeman",
    "team": "",
    "position": "G",
    "height": "5-8",
    "jersey": "",
    "wnbaTeam": "Seattle Storm",
    "profile": "https://www.unrivaled.basketball/player/natisha-hiedeman-okjofgwlkna9",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/natisha-hiedeman/images/headshot.jpg?v=1767477467898"
  },
  {
    "id": "naz-hillmon-06yn0bxvvzhx",
    "name": "Naz Hillmon",
    "team": "",
    "position": "F",
    "height": "6-2",
    "jersey": "",
    "wnbaTeam": "Atlanta Dream",
    "profile": "https://www.unrivaled.basketball/player/naz-hillmon-06yn0bxvvzhx",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/naz-hillmon/images/headshot.jpg?v=1767477611125"
  },
  {
    "id": "rhyne-howard-4oadwt7gp636",
    "name": "Rhyne Howard",
    "team": "",
    "position": "W",
    "height": "6-2",
    "jersey": "",
    "wnbaTeam": "Atlanta Dream",
    "profile": "https://www.unrivaled.basketball/player/rhyne-howard-4oadwt7gp636",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/rhyne-howard/images/headshot.jpg?v=1767478308082"
  },
  {
    "id": "lexie-hull-bh6vgd8htw6a",
    "name": "Lexie Hull",
    "team": "",
    "position": "W",
    "height": "6-1",
    "jersey": "",
    "wnbaTeam": "Indiana Fever",
    "profile": "https://www.unrivaled.basketball/player/lexie-hull-bh6vgd8htw6a",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/lexie-hull/images/headshot.jpg?v=1767477944760"
  },
  {
    "id": "rickea-jackson-tuum4vu1htu2",
    "name": "Rickea Jackson",
    "team": "",
    "position": "W",
    "height": "6-2",
    "jersey": "",
    "wnbaTeam": "Chicago Sky",
    "profile": "https://www.unrivaled.basketball/player/rickea-jackson-tuum4vu1htu2",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/rickea-jackson/images/headshot.jpg?v=1768148280622"
  },
  {
    "id": "aziaha-james-qkhnkbzlf4j2",
    "name": "Aziaha James",
    "team": "",
    "position": "G",
    "height": "",
    "jersey": "",
    "wnbaTeam": "Dallas Wings",
    "profile": "https://www.unrivaled.basketball/player/aziaha-james-qkhnkbzlf4j2",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/aziaha-james/images/headshot.jpg?v=1767477281608"
  },
  {
    "id": "marine-johannes-0z40b9zire54",
    "name": "Marine Johannès",
    "team": "",
    "position": "",
    "height": "",
    "jersey": "",
    "wnbaTeam": "New York Liberty",
    "profile": "https://www.unrivaled.basketball/player/marine-johannes-0z40b9zire54",
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4038379.png"
  },
  {
    "id": "flaujae-johnson-2j3q3ows2dkl",
    "name": "Flau'jae Johnson",
    "team": "",
    "position": "",
    "height": "",
    "jersey": "",
    "wnbaTeam": "Seattle Storm",
    "profile": "https://www.unrivaled.basketball/player/flaujae-johnson-2j3q3ows2dkl",
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4698736.png"
  },
  {
    "id": "marina-mabrey-fj1hf0z16u7d",
    "name": "Marina Mabrey",
    "team": "",
    "position": "W",
    "height": "5-11",
    "jersey": "",
    "wnbaTeam": "Toronto Tempo",
    "profile": "https://www.unrivaled.basketball/player/marina-mabrey-fj1hf0z16u7d",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/marina-mabrey/images/headshot.jpg?v=1767477692641"
  },
  {
    "id": "ezi-magbegor-oyzb1q1fldpl",
    "name": "Ezi Magbegor",
    "team": "",
    "position": "F",
    "height": "6-4",
    "jersey": "",
    "wnbaTeam": "Seattle Storm",
    "profile": "https://www.unrivaled.basketball/player/ezi-magbegor-oyzb1q1fldpl",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/ezi-magbegor/images/headshot.jpg?v=1767477474445"
  },
  {
    "id": "dominique-malonga-15pjdtbbffgx",
    "name": "Dominique Malonga",
    "team": "",
    "position": "F",
    "height": "6-6",
    "jersey": "",
    "wnbaTeam": "Seattle Storm",
    "profile": "https://www.unrivaled.basketball/player/dominique-malonga-15pjdtbbffgx",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/dominique-malonga/images/headshot.jpg?v=1767477373485"
  },
  {
    "id": "kate-martin-hron1sg1muj7",
    "name": "Kate Martin",
    "team": "",
    "position": "W",
    "height": "6-0",
    "jersey": "",
    "wnbaTeam": "Chicago Sky",
    "profile": "https://www.unrivaled.basketball/player/kate-martin-hron1sg1muj7",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/kate-martin/images/headshot.jpg?v=1767477366471"
  },
  {
    "id": "kayla-mcbride-8jp766iviaj1",
    "name": "Kayla McBride",
    "team": "",
    "position": "W",
    "height": "5-11",
    "jersey": "",
    "wnbaTeam": "Minnesota Lynx",
    "profile": "https://www.unrivaled.basketball/player/kayla-mcbride-8jp766iviaj1",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/kayla-mcbride/images/headshot.jpg?v=1738721488557"
  },
  {
    "id": "olivia-miles-t56qpvaq0ryv",
    "name": "Olivia Miles",
    "team": "",
    "position": "",
    "height": "",
    "jersey": "",
    "wnbaTeam": "Minnesota Lynx",
    "profile": "https://www.unrivaled.basketball/player/olivia-miles-t56qpvaq0ryv",
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433791.png"
  },
  {
    "id": "aneesah-morrow-iwx9hxzuk8kj",
    "name": "Aneesah Morrow",
    "team": "",
    "position": "",
    "height": "",
    "jersey": "",
    "wnbaTeam": "Toronto Tempo",
    "profile": "https://www.unrivaled.basketball/player/aneesah-morrow-iwx9hxzuk8kj",
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4684384.png"
  },
  {
    "id": "arike-ogunbowale-r9p1g69osavq",
    "name": "Arike Ogunbowale",
    "team": "",
    "position": "W",
    "height": "5-8",
    "jersey": "",
    "wnbaTeam": "Dallas Wings",
    "profile": "https://www.unrivaled.basketball/player/arike-ogunbowale-r9p1g69osavq",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/arike-ogunbowale/images/headshot.jpg?v=1767477796609"
  },
  {
    "id": "kelsey-plum-trxk8xrmxs29",
    "name": "Kelsey Plum",
    "team": "",
    "position": "G",
    "height": "5-8",
    "jersey": "",
    "wnbaTeam": "Phoenix Mercury",
    "profile": "https://www.unrivaled.basketball/player/kelsey-plum-trxk8xrmxs29",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/kelsey-plum/images/headshot.jpg?v=1767478086341"
  },
  {
    "id": "kiki-rice-wzl0620iift5",
    "name": "Kiki Rice",
    "team": "",
    "position": "",
    "height": "",
    "jersey": "",
    "wnbaTeam": "Toronto Tempo",
    "profile": "https://www.unrivaled.basketball/player/kiki-rice-wzl0620iift5",
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4565505.png"
  },
  {
    "id": "satou-sabally-0ygbxjbwjcpd",
    "name": "Satou Sabally",
    "team": "",
    "position": "W",
    "height": "6-4",
    "jersey": "",
    "wnbaTeam": "New York Liberty",
    "profile": "https://www.unrivaled.basketball/player/satou-sabally-0ygbxjbwjcpd",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/satou-sabally/images/headshot.jpg?v=1738721451865"
  },
  {
    "id": "jessica-shepard-756yb020vyet",
    "name": "Jessica Shepard",
    "team": "",
    "position": "",
    "height": "",
    "jersey": "",
    "wnbaTeam": "Dallas Wings",
    "profile": "https://www.unrivaled.basketball/player/jessica-shepard-756yb020vyet",
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3906949.png"
  },
  {
    "id": "maddy-siegrist-2b11qo1xprtv",
    "name": "Maddy Siegrist",
    "team": "",
    "position": "W",
    "height": "6-2",
    "jersey": "",
    "wnbaTeam": "Dallas Wings",
    "profile": "https://www.unrivaled.basketball/player/maddy-siegrist-2b11qo1xprtv",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/maddy-siegrist/images/headshot.jpg?v=1767477596696"
  },
  {
    "id": "breanna-stewart-lqj6yuo4sk42",
    "name": "Breanna Stewart",
    "team": "",
    "position": "F",
    "height": "6-4",
    "jersey": "",
    "wnbaTeam": "New York Liberty",
    "profile": "https://www.unrivaled.basketball/player/breanna-stewart-lqj6yuo4sk42",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/breanna-stewart/images/headshot.jpg?v=1767477811234"
  },
  {
    "id": "brittney-sykes-5r0ujro9gsjp",
    "name": "Brittney Sykes",
    "team": "",
    "position": "W",
    "height": "5-9",
    "jersey": "",
    "wnbaTeam": "Toronto Tempo",
    "profile": "https://www.unrivaled.basketball/player/brittney-sykes-5r0ujro9gsjp",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/brittney-sykes/images/headshot.jpg?v=1767477574674"
  },
  {
    "id": "sydney-taylor-dly9mrswsxoo",
    "name": "Sydney Taylor",
    "team": "",
    "position": "",
    "height": "",
    "jersey": "",
    "wnbaTeam": "Chicago Sky",
    "profile": "https://www.unrivaled.basketball/player/sydney-taylor-dly9mrswsxoo",
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4594786.png"
  },
  {
    "id": "kayla-thornton-mu518tg49vul",
    "name": "Kayla Thornton",
    "team": "",
    "position": "",
    "height": "",
    "jersey": "",
    "wnbaTeam": "Golden State Valkyries",
    "profile": "https://www.unrivaled.basketball/player/kayla-thornton-mu518tg49vul",
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2529622.png"
  },
  {
    "id": "gabby-williams-8qyinsyrymnw",
    "name": "Gabby Williams",
    "team": "",
    "position": "",
    "height": "",
    "jersey": "",
    "wnbaTeam": "Golden State Valkyries",
    "profile": "https://www.unrivaled.basketball/player/gabby-williams-8qyinsyrymnw",
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3142328.png"
  },
  {
    "id": "courtney-williams-v723cso81wi3",
    "name": "Courtney Williams",
    "team": "",
    "position": "G",
    "height": "5-8",
    "jersey": "",
    "wnbaTeam": "Minnesota Lynx",
    "profile": "https://www.unrivaled.basketball/player/courtney-williams-v723cso81wi3",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/courtney-williams/images/headshot.jpg?v=1771538691081"
  },
  {
    "id": "jackie-young-cbba3mtca702",
    "name": "Jackie Young",
    "team": "",
    "position": "G",
    "height": "6-0",
    "jersey": "",
    "wnbaTeam": "Las Vegas Aces",
    "profile": "https://www.unrivaled.basketball/player/jackie-young-cbba3mtca702",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/jackie-young/images/headshot.jpg?v=1767477588586"
  },
  {
    "id": "li-yueru-biqged5f7r22",
    "name": "Li Yueru",
    "team": "",
    "position": "F",
    "height": "6-7",
    "jersey": "",
    "wnbaTeam": "Dallas Wings",
    "profile": "https://www.unrivaled.basketball/player/li-yueru-biqged5f7r22",
    "headshot": "https://pub-ad8cc693759b4b55a181a76af041efa0.r2.dev/players/li-yueru/images/headshot.jpg?v=1767477815740"
  }
];
